# Generated by Django 4.1.1 on 2022-12-04 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pin', models.CharField(max_length=6, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=20, null=True)),
                ('last_name', models.CharField(max_length=20, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='images/logo-round.jpg', null=True, upload_to='images/')),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('tasks_finished', models.IntegerField(default=0, verbose_name='tasks finished')),
                ('xp', models.IntegerField(default=0, verbose_name='xp')),
                ('level', models.IntegerField(default=0)),
                ('nextLevelThresh', models.IntegerField(default=200)),
                ('prevLevelThresh', models.IntegerField(default=0)),
                ('xpToNextLevel', models.IntegerField(default=200)),
                ('highestLevelReached', models.IntegerField(default=0)),
                ('lootboxes', models.IntegerField(default=0, verbose_name='lootboxes')),
                ('fortnight_xp', models.IntegerField(default=0)),
                ('household', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.household')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('creation_time', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('points', models.IntegerField()),
                ('claimed', models.BooleanField(default=False)),
                ('in_progress', models.BooleanField(default=False)),
                ('task_status', models.BooleanField(default=False)),
                ('household', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household')),
                ('user_claimed', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_user_claimed', to='users.profile')),
                ('user_created', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_user_created', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=8)),
                ('mo', models.BooleanField(default=False)),
                ('tu', models.BooleanField(default=False)),
                ('we', models.BooleanField(default=False)),
                ('th', models.BooleanField(default=False)),
                ('fr', models.BooleanField(default=False)),
                ('sa', models.BooleanField(default=False)),
                ('su', models.BooleanField(default=False)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('task_to_clone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='Lootbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(blank=True, max_length=55, null=True)),
                ('noun', models.CharField(blank=True, max_length=55, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lootbox_owner', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('bulletin_body', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('expire_date', models.DateTimeField()),
                ('household', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household')),
            ],
        ),
    ]
