# Generated by Django 4.0.7 on 2022-10-26 02:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('datetime', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('household_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='NO NAME!', max_length=30)),
                ('pin', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('points', models.IntegerField(default=0, verbose_name='points')),
                ('tasks_finished', models.IntegerField(default=0, verbose_name='tasks finished')),
                ('household', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('due_date', models.DateTimeField()),
                ('points', models.IntegerField()),
                ('claimed', models.BooleanField(default=False)),
                ('task_status', models.BooleanField(default=False)),
                ('household', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household')),
                ('user_claimed', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_user_claimed', to='users.profile')),
                ('user_created', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_user_created', to='users.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=8)),
                ('mo', models.BooleanField(default=False)),
                ('tu', models.BooleanField(default=False)),
                ('we', models.BooleanField(default=False)),
                ('th', models.BooleanField(default=False)),
                ('fr', models.BooleanField(default=False)),
                ('sa', models.BooleanField(default=False)),
                ('su', models.BooleanField(default=False)),
                ('day_of_month', models.IntegerField(blank=True, null=True)),
                ('task_to_clone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.task')),
            ],
        ),
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=100)),
                ('bulletin_body', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField()),
                ('expire_time', models.DateTimeField()),
                ('household', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.household')),
            ],
        ),
    ]
