# Generated by Django 4.0.7 on 2022-10-19 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='household',
            old_name='messages',
            new_name='bulletins',
        ),
    ]
