# Generated by Django 4.0.7 on 2022-12-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
