# Generated by Django 4.1.1 on 2022-10-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_messages_household_bulletins'),
    ]

    operations = [
        migrations.AddField(
            model_name='chore',
            name='task_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chore',
            name='user_claimed',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_user_claimed', to='users.profile'),
        ),
        migrations.AddField(
            model_name='chore',
            name='user_created',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chore_user_created', to='users.profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='points'),
        ),
        migrations.AddField(
            model_name='profile',
            name='tasks_finished',
            field=models.IntegerField(default=0, verbose_name='tasks finished'),
        ),
    ]
