# Generated by Django 4.0.7 on 2022-12-04 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_task_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletin',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bulletin_user', to='users.profile'),
        ),
    ]
