# Generated by Django 4.1.1 on 2022-10-26 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_household'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='household',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='members', to='users.household'),
        ),
    ]
