# Generated by Django 4.0.7 on 2022-10-25 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_chore_task_status_chore_user_claimed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=8)),
                ('mo', models.BooleanField(default=False)),
                ('tu', models.BooleanField(default=False)),
                ('we', models.BooleanField(default=False)),
                ('th', models.BooleanField(default=False)),
                ('fr', models.BooleanField(default=False)),
                ('sa', models.BooleanField(default=False)),
                ('su', models.BooleanField(default=False)),
                ('day_of_month', models.IntegerField(blank=True)),
                ('task_to_clone', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='users.chore')),
            ],
        ),
    ]
