# Generated by Django 4.0.7 on 2022-12-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_user_bulletin_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='kudos',
            field=models.BooleanField(default=False),
        ),
    ]
