# Generated by Django 4.0.7 on 2022-10-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_taskrecurrence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskrecurrence',
            name='day_of_month',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
