# Generated by Django 4.0.7 on 2022-11-08 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='nextLevelThresh',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='prevLevelThresh',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='xp',
            field=models.IntegerField(default=0, verbose_name='xp'),
        ),
        migrations.AddField(
            model_name='profile',
            name='xpToNextLevel',
            field=models.IntegerField(default=1000),
        ),
    ]
