# Generated by Django 4.0.7 on 2022-12-05 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_task_kudos'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='adjective',
            field=models.CharField(default='No', max_length=55, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noun',
            field=models.CharField(blank='Nickname', max_length=55, null=True),
        ),
    ]
