# Generated by Django 4.1.1 on 2022-10-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_chore_event_rename_household_profile_household_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bulletin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(max_length=500)),
                ('bulletin_body', models.CharField(max_length=500)),
                ('creation_time', models.DateTimeField(auto_now=True)),
                ('expire_time', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='household_code',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AlterField(
            model_name='household',
            name='messages',
            field=models.ManyToManyField(to='users.bulletin'),
        ),
    ]
