# Generated by Django 4.1.1 on 2022-11-09 04:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_task_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='creation_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
