# Generated by Django 4.1.1 on 2022-10-05 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bulletin_remove_profile_household_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin',
            old_name='sender',
            new_name='user',
        ),
    ]
