# Generated by Django 4.1.3 on 2022-11-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_task_in_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lootboxes',
            field=models.IntegerField(default=0, verbose_name='lootboxes'),
        ),
        migrations.CreateModel(
            name='LootBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjective', models.CharField(blank=True, max_length=55, null=True)),
                ('noun', models.CharField(blank=True, max_length=55, null=True)),
                ('owner', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lootbox_owner', to='users.profile')),
            ],
        ),
    ]
