# Generated by Django 4.0.7 on 2022-12-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_adjective_profile_noun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='noun',
            field=models.CharField(default='Nickname', max_length=55, null=True),
        ),
    ]
