# Generated by Django 4.1.3 on 2022-11-16 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_bulletin_creation_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletin',
            old_name='expire_time',
            new_name='expire_date',
        ),
    ]
