# Generated by Django 4.1.1 on 2022-10-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_sender_bulletin_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='name',
            field=models.CharField(default='NO NAME!', max_length=30),
        ),
        migrations.AddField(
            model_name='household',
            name='pin',
            field=models.IntegerField(default=12345),
        ),
        migrations.AlterField(
            model_name='bulletin',
            name='creation_time',
            field=models.DateTimeField(),
        ),
    ]
