# Generated by Django 4.1.1 on 2022-10-12 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_household_name_household_pin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='chores',
            field=models.ManyToManyField(blank=True, to='users.chore'),
        ),
        migrations.AlterField(
            model_name='household',
            name='events',
            field=models.ManyToManyField(blank=True, to='users.event'),
        ),
        migrations.AlterField(
            model_name='household',
            name='messages',
            field=models.ManyToManyField(blank=True, to='users.bulletin'),
        ),
        migrations.AlterField(
            model_name='household',
            name='profiles',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
    ]
