# Generated by Django 4.1.1 on 2022-10-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_household_chores_alter_household_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='pin',
            field=models.IntegerField(unique=True),
        ),
    ]
