# Generated by Django 4.0.7 on 2022-11-16 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_first_name_alter_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='name',
        ),
        migrations.AlterField(
            model_name='household',
            name='pin',
            field=models.CharField(max_length=6, unique=True),
        ),
    ]
