# Generated by Django 4.0.7 on 2022-11-16 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_remove_household_name_alter_household_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='household',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='users.household'),
        ),
    ]
