# Generated by Django 4.1.2 on 2022-11-16 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_profile_lootboxes_lootbox'),
        ('users', '0011_alter_profile_household'),
    ]

    operations = [
    ]
