# Generated by Django 4.0.7 on 2022-11-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_profile_profile_picture'),
        ('users', '0012_merge_20221116_2044'),
    ]

    operations = [
    ]
