# Generated by Django 4.0.7 on 2022-11-20 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_expire_time_bulletin_expire_date'),
        ('users', '0013_merge_20221120_1944'),
    ]

    operations = [
    ]
