# Generated by Django 4.0.7 on 2022-11-27 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_merge_20221120_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fortnite_xp',
            field=models.IntegerField(default=0),
        ),
    ]
