# Generated by Django 4.0.7 on 2022-11-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_fortnite_xp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='fortnite_xp',
            new_name='fortnight_xp',
        ),
    ]
